---
# 7-Zip exe doesn't use a guid for the Product ID
- name: Install Windows MSI
  hosts: windows
  tasks:
    - name: Install 7zip from a internet
      win_package:
        path: C:\Users\Public\7z1805-x64.msi
        state: absent
